name: hf10
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - aiofiles=23.2.1
  - aiohappyeyeballs=2.5.0
  - aiohttp=3.11.13
  - aiosignal=1.3.2
  - alembic=1.15.1
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - anyio=4.8.0
  - aom=3.9.1
  - arrow=1.3.0
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.1.0
  - audioread=3.0.1
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - binaryornot=0.4.4
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - colorlog=6.9.0
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=3.3.2
  - dav1d=1.2.1
  - dbus=1.13.6
  - decorator=5.2.1
  - dill=0.3.8
  - dnspython=2.7.0
  - double-conversion=3.3.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - evaluate=0.4.3
  - exceptiongroup=1.2.2
  - expat=2.6.4
  - fastapi=0.115.11
  - fastapi-cli=0.0.7
  - ffmpeg=7.1.1
  - ffmpy=0.3.0
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gdk-pixbuf=2.42.12
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gradio=5.16.1
  - gradio-client=1.7.0
  - graphite2=1.3.13
  - greenlet=3.1.1
  - grpcio=1.67.1
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - huggingface_hub=0.29.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - intel-openmp=2022.0.1
  - jack=1.9.22
  - jinja2=3.1.6
  - joblib=1.4.2
  - kaldi=5.5.1112
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - level-zero=1.21.1
  - libabseil=20240722.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.13.1.3
  - libcups=2.3.3
  - libcurand=10.3.9.90
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.51
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.3.1
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librosa=0.10.2.post1
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.3
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libudev1=257.3
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.27
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - mako=1.3.9
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mdurl=0.1.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.4
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - numba=0.61.0
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openfst=1.8.3
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - optuna=4.2.1
  - orc=2.1.1
  - orjson=3.10.15
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.1
  - patsy=1.0.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prometheus-cpp=1.3.0
  - propcache=0.2.1
  - protobuf=5.28.3
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pydub=0.25.1
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-multipart=0.0.20
  - python-slugify=8.0.4
  - python-tzdata=2025.1
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - ruff=0.9.9
  - s2n=1.5.11
  - safehttpx=0.1.6
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.50
  - sdl3=3.2.8
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - semantic_version=2.10.0
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - sqlalchemy=2.0.38
  - sqlite=3.32.3
  - starlette=0.46.0
  - statsmodels=0.14.4
  - svt-av1=3.0.0
  - sympy=1.13.3
  - tbb=2022.0.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomlkit=0.13.2
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - transformers=4.49.0
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.21.0
  - watchfiles=1.0.4
  - wayland=1.23.1
  - wayland-protocols=1.41
  - websockets=12.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.3
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.4.0
      - psutil==7.0.0
